/* eslint-disable @next/next/no-img-element */
import React, { ContextType, useEffect, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Nav from "../components/Nav";
import Header from "../components/loginPage/Header";
import Login from "../components/loginPage/Login";
import { getToken } from "../utils/spotify-auth";
import SpotifyWebApi from "spotify-web-api-js";
import { useDataContextVal } from "../context/dataContext";
import { updateUserData } from "../context/actions";
import MoodHome from "../components/MoodHome";
import Layout from "../components/Layout";

const spotifyWeb = new SpotifyWebApi();

const Home: NextPage = () => {
  const [{ user }, dispatch] = useDataContextVal();
  const [token, setToken] = useState(null);

  const setUser = () => {
    //get object containing the acesstoken
    !token &&
      getToken().then((resp) => {
        console.log(resp);
        setToken(resp?.access_token);
      });
    console.log(token);

    if (token) {
      localStorage.setItem("token", token);
      spotifyWeb.setAccessToken(token);
      //set the location of the window back without the code
      // window.location.pathname = "";

      //after setting the accesstoken for aouth, get user and dispatch updated data
      //add error catch incase user can't be found as a popup?
      // spotifyWeb.setAccessToken();
      spotifyWeb
        .getMe()
        .then((user) => {
          localStorage.setItem("user", JSON.stringify(user)),
            dispatch(updateUserData(user));
        })
        .catch((err) => console.log(err));
    }
  };

  useEffect(() => {
    /*get user from localstorage
    if present dispatch else call set user data
    */
    let user = JSON.parse(localStorage.getItem("user"));
    user ? dispatch(updateUserData(user)) : setUser();
  }, []);

  return (
    <div>
      <Head>
        <title>Gbedu Vibes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/conga.svg" />
      </Head>

      <main className="">
        <Layout>
          <div className="pt-6 px-6 md:px-20 sm:px-12">
            <Nav showTeam={true} />
            {user?.display_name ? (
              <MoodHome />
            ) : (
              <>
                <Header />
                <div className="flex items-center justify-center pt-8">
                  <Login />
                </div>
              </>
            )}
          </div>
        </Layout>
      </main>
    </div>
  );
};

export default Home;
